replicaCount: 3

image:
  repository: registry.digitalocean.com/abd-registry/formlabs
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

resources: {}                 

podAnnotations: {}

livenessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /
  initialDelaySeconds: 3
  periodSeconds: 5
